### ISSUE TITLE
mouse delta x/y calulation wrong if update is slow

### ISSUE THREAD

**Issue by the-sz** [peteroupc/html3dutil#2]
if there are many objects and the update is slow, the delta x/y calculation is wrong on mousedown if happen right after a mousemove.

to fix this add
   if(e.button!=-1){
     thisObj.lastClient[0]=thisObj.clientX;
     thisObj.lastClient[1]=thisObj.clientY;
   }
in camera.js line 405

**Comment by peteroupc** [comment]
Your change appears to work.  If you agree to release your contribution to the public domain, you should submit a pull request.
