### ISSUE TITLE
New demos needed

### ISSUE THREAD

**Issue by peteroupc** [peteroupc/html3dutil#5]
I already have [several demos](https://github.com/peteroupc/html3dutil/blob/master/README.md) showing the various possibilities with my Public Domain HTML 3D Library.

I would like people to suggest or make new demos to add to the list.  This is also a very good opportunity for you to test the library and see if everything works.  If you make a new demo, you must release it to the Public Domain before I can add it.

**Comment by philwilson** [comment]
Hey peter. I was just trying to look through those demos but actually none of them are working.
The console in chrome shows
`Uncaught SyntaxError: Unexpected token <<              glutil_min.js:53`
`Uncaught ReferenceError: Scene3D is not defined     obj.html:33 
`
when trying the first one (demos/simple.html) and the rest show similar.

**Comment by peteroupc** [comment]
@philwilson:

The issue should be resolved by now.  Next time, open a separate issue if you have problems with this library or its demos.

**Comment by peteroupc** [comment]
Closing this.  This library's focus is going to change.
