### ISSUE TITLE
Missing demo resources

### ISSUE THREAD

**Issue by dakics** [peteroupc/html3dutil#6]
Hi Peter

Many of the demos result in black screen. This is from developer console (Chrome):

`simple.html:25 Uncaught ReferenceError: Subscene3D is not defined`

Some end up with a different problem, pathtube for example.

`glutil_min.js:92 Uncaught TypeError: this.bufferedMesh._getBounds is not a function`

Thank you for the great work BTW. 
Srdjan

**Comment by peteroupc** [comment]
I’m in the process of decoupling textures, meshes, shapes, etc. from WebGL resources.  Subscene3D is among the new classes created for this purpose.  Not all the demos have been modified to match yet. If you want to try this library, see the Releases page (however, the classes and functionality they use are likely to be deprecated in the next version.)
